[package]
edition = "2021"
name = "modern_swc_plugins_utils"
version = "0.1.0"


[dependencies]
swc_core = { workspace = true, features = [
  "common",
  "ecma_ast",
  "ecma_visit",
  "ecma_transforms",
  "ecma_quote",
] }
rustc-hash = { workspace = true }
